export const SAMPLE_TEXTS: { title: string; text: string }[] = [
  {
    title: 'Párrafo corto',
    text: 'La lectura veloz es una habilidad que se puede entrenar con práctica diaria. Cualquier persona puede duplicar su velocidad manteniendo la comprensión si aprende a eliminar la subvocalización y usar la visión periférica. Un método muy útil es el chunking, que consiste en leer grupos de palabras en lugar de una sola cada vez. Otro consejo importante es evitar regresar constantemente a frases anteriores, porque eso rompe el ritmo. También ayuda usar un puntero o el dedo para guiar la vista y evitar saltos innecesarios. Con el tiempo, el cerebro se acostumbra a procesar bloques completos y la lectura se vuelve más fluida. Muchas personas creen que leer rápido significa perder comprensión, pero eso solo ocurre cuando se fuerza la velocidad sin técnica. En cambio, con entrenamiento gradual se logra ir más rápido sin sacrificar el entendimiento. Una sesión corta todos los días genera mejores resultados que una sesión larga solo una vez por semana. Lo ideal es empezar despacio, medir el progreso y aumentar la dificultad de forma constante. La postura también influye: una silla cómoda, buena luz y una distancia adecuada reducen la fatiga visual. Finalmente, es útil elegir textos variados para no aburrirse y mantener la concentración durante la práctica.',
  },
  {
    title: 'Ciencia',
    text: 'La fotosíntesis convierte la luz solar en energía química dentro de las hojas. Las neuronas procesan señales eléctricas y químicas mediante impulsos nerviosos. Un dinosaurio enorme caminaba despacio aprovechando su masa corporal. La termodinámica estudia el calor, el trabajo y la energía en los sistemas físicos. Un desoxirribonucleico almacena la herencia genética completa de un organismo. Observa una bacteria diminuta bajo el microscopio para ver su forma alargada. Las células regeneran tejidos dañados mediante procesos de división y reparación. Un ecosistema equilibrado sostiene la vida porque cada especie cumple una función. La astronomía explora el universo infinito con telescopios cada vez más potentes. Un volcán libera magma, ceniza y gases tóxicos durante una erupción violenta. Las placas tectónicas se desplazan lentamente y generan terremotos en los límites continentales. Un compuesto químico puede cambiar de estado sólido a líquido al aumentar la temperatura. La óptica estudia la luz, las sombras, los reflejos y los fenómenos de refracción. Una molécula de agua está formada por dos átomos de hidrógeno y uno de oxígeno. Los rayos gamma son radiaciones muy energéticas provenientes del espacio exterior. Un ecosistema acuático depende del oxígeno disuelto, la temperatura y la salinidad del agua. Una bacteria puede duplicarse en minutos si encuentra nutrientes suficientes en su entorno.',
  },
  {
    title: 'Ciudad',
    text: 'Las ciudades modernas son ecosistemas complejos donde millones de personas conviven en espacios reducidos. El transporte público, la energía eléctrica, los residuos urbanos y la comunicación forman redes invisibles que sostienen la vida cotidiana. Planificar ciudades sostenibles es el reto del siglo XXI, porque el crecimiento acelerado genera tráfico, contaminación y desigualdad. Los edificios inteligentes ahora regulan el consumo energético de forma automática. Un parque urbano mejora la calidad del aire y ofrece refugio en días calurosos. El transporte masivo reduce la cantidad de coches particulares en las avenidas principales. La recolección de basura puerta a puerta evita acumulación de residuos en las calles. Un semáforo sincronizado disminuye las horas de congestión en horas pico. Las bicisendas protegen a los ciclistas y fomentan la movilidad activa. Un mercado local conecta a productores y vecinos sin intermediarios costosos. Las ciudades inteligentes usan sensores para monitorear el ruido, el agua y la energía. Una plaza central se convierte en punto de encuentro y expresión cultural. El transporte subterráneo viaja rápido sin interferir con el tránsito superficial. Un edificio verde consume menos electricidad gracias al aislamiento térmico. La iluminación led ahorra energía en espacios públicos y privados. Un puente peatonal mejora la seguridad de quienes caminan por zonas peligrosas. La planificación urbana debe incluir vivienda accesible para evitar desplazamientos injustos. Un sistema de reciclaje eficiente transforma residuos en materiales reutilizables.',
  },
  {
    title: 'Motivación',
    text: 'Cada día es una nueva oportunidad para mejorar si mantienes el foco en tus objetivos. No importa cuántas veces hayas fallado, porque lo realmente importante es intentarlo de nuevo con una estrategia distinta. La constancia vence al talento cuando el talento no es constante y se queda solo en la intención. Tú eres capaz de más de lo que imaginas si divides las metas en pasos pequeños y ejecutables. Un hábito poderoso es escribir cada mañana las tres prioridades del día antes de revisar mensajes. Cuando enfrentas una tarea difícil, divide el trabajo en bloques cortos para no abrumarte. Celebrar pequeños avances mantiene alta la motivación durante proyectos largos y exigentes. Un error no es una derrota sino información valiosa para ajustar el rumbo. Rodearte de personas comprometidas contagia disciplina y reduce la procrastinación. La paciencia también es una forma de acción cuando los resultados tardan en llegar. Es útil recordar por qué empezaste cuando el proceso se vuelve tedioso o confuso. Cada repetición fortalece el camino hacia la maestría y reduce la fricción futura. Una rutina matutina sencilla predispone al cerebro a concentrarse antes del mediodía. Cuando algo no sale bien, cambia el método en vez de abandonar la meta. Visualizar el resultado deseado durante unos minutos aumenta la confianza antes de empezar. Un diario de progreso permite ver claramente cuánto avanzaste semana tras semana.',
  },
  {
    title: 'Naturaleza',
    text: 'Los bosques son los pulmones del planeta porque producen oxígeno y capturan dióxido de carbono. Árboles centenarios, ríos cristalinos y una biodiversidad infinita crean un equilibrio perfecto que sostiene la vida silvestre. Proteger la naturaleza no es opcional, es nuestra responsabilidad como especie frente a las próximas generaciones. Un arrecife de coral alberga miles de especies en un espacio relativamente pequeño. La selva tropical regula el clima global y conserva bancos genéticos únicos. Un río subterráneo transporta agua dulce durante kilómetros sin que lo veamos. Los suelos fértiles permiten cultivar alimentos sin dañar el entorno natural. Un ave migratoria recorre continentes enteros siguiendo rutas ancestrales. La montaña retiene agua en su cumbre y la libera gradualmente hacia los valles. Una semilla puede permanecer dormida hasta que encuentra las condiciones ideales para brotar. La Luna influye en las mareas, los cultivos y el comportamiento animal nocturno. Un humedal filtra toxinas y funciona como guardería natural para peces y aves. El invierno reduce la actividad exterior, pero la naturaleza sigue transformándose bajo la nieve. Un bosque nublado genera neblina constante gracias a la evaporación de las plantas. La conservación de especies amenazadas depende de hábitats protegidos y conectados entre sí.',
  },
  {
    title: 'Tecnología',
    text: 'La computación cuántica redefine el cálculo tradicional mediante qubits y superposición. Una inteligencia artificial aprende rápido cuando recibe datos limpios y objetivos claros. La ciberseguridad protege datos sensibles mediante cifrado, autenticación y monitoreo continuo. Un blockchain registra transacciones en bloques enlazados sin necesidad de un intermediario central. Un dron liviano sobrevuela la ciudad para entregar paquetes, inspeccionar estructuras o mapear zonas amplias. La programación transforma ideas en realidad cuando se combinan algoritmos, interfaces y bases de datos. Un algoritmo optimiza procesos industriales reduciendo desperdicios y tiempos de producción. La realidad aumentada mezcla mundos digitales con el entorno físico mediante gafas o pantallas inteligentes. Una impresora tridimensional crea objetos físicos capa por capa a partir de un modelo digital. Un sensor IoT detecta temperatura, humedad o movimiento y envía esa información a la nube. La automatización permite que máquinas realicen tareas repetitivas con alta precisión y bajo error. Un centro de datos aloja servidores que soportan millones de consultas cada minuto. La conectividad 5G reduce la latencia y mejora la transferencia de información en tiempo real. Un prototipo funcional acorta el camino entre la idea inicial y el producto final. La minería de datos descubre patrones ocultos dentro de grandes volúmenes de información. Un robot colaborativo trabaja junto a personas en fábricas sin necesidad de jaulas de seguridad.',
  },
];

export const HISTORY_TEXTS: Record<string, { title: string; text: string }> = {
  primeros_seres_humanos: {
    title: 'Primeros seres humanos',
    text: 'Hace millones de años no existían ciudades ni escritura. Los primeros seres humanos vivían en África y se parecían a los simios. Caminaban a dos piernas, usaban piedras como herramientas y vivían en grupos pequeños. A esta etapa la llamamos prehistoria porque no hay escritura que cuente lo que pasó. Un hallazgo muy importante fue Lucy. En 1974, científicos encontraron en Etiopía los huesos de una hembra de Australopithecus. Tenía más de tres millones de años. Medía un metro y pesaba veintisiete kilos. Su cerebro era pequeño pero ya caminaba erguida. Lucy nos enseña que los humanos evolucionaron lentamente. Otro hallazgo son las pinturas rupestres. En cuevas de Europa y África se encontraron dibujos de animales y manos hechas hace miles de años. Estos dibujos demuestran que los primeros humanos ya tenían capacidad de expresión y pensamiento. Durante la prehistoria, los grupos humanos eran pequeños y se moveban constantemente buscando comida. Usaban piedras afiladas, huesos y madera para crear las primeras herramientas.',
  },
  vida_nomada: {
    title: 'Vida nómada',
    text: 'Hace mucho tiempo los seres humanos no tenían casa fija. Eran nómadas, es decir, se movían de un lugar a otro. Su alimentación dependía de lo que encontraran. Cazaban animales como mamuts y recolectaban frutas, raíces y semillas. Los mamuts eran gigantes con pelaje largo. Parecidos a los elefantes, migraron de África hace millones de años. Los cazadores los perseguían hasta que quedaban atrapados en pantanos. Luego les lanzaban lanzas y flechas. En la cuenca de México también vivían mamuts, ya que el clima era similar al de una sabana con lagos. Los huesos de estos animales se han encontrado en lo que hoy es la Ciudad de México. La caza era peligrosa y la comida no siempre abundaba. Por eso los grupos nómadas desarrollaron gran capacidad de observación y memoria. Conocían cada planta, cada rastro de animal y cada cambio de estación. La vida nómada requería cooperación: todos trabajaban para la supervivencia del grupo.',
  },
  nomadismo_sedentarismo: {
    title: 'Sedentarismo',
    text: 'Hace unos diez mil años ocurrió un cambio fundamental. Algunos grupos nómadas empezaron a cultivar plantas y domesticar animales. Ya no necesitaban moverse constantemente para encontrar comida. Podían quedarse en un lugar y producir su propio alimento. Así nació la agricultura y con ella los primeros asentamientos permanentes. La gente construyó casas de adobe, creó almacenes para guardar cosechas y desarrolló nuevas herramientas como la hoz y el mortero. La sedentarización trajo especialización: no todos debían cultivar, algunos se dedicaban a la cerámica, el tejido o la metalurgia. Surgieron los primeros pueblos y luego las primeras ciudades. La escritura apareció para llevar cuentas de la producción y el comercio. La humanidad había entrado en una nueva era: la historia.',
  },
};